### ISSUE TITLE
iOS tokbox core SDK crashing

### ISSUE THREAD

**Issue by laeroah** [opentok/interactive-broadcast-ios#7]
Using OpenTok (2.12.1)
iOS 11
We got 207 crashes happen last night during one relative busy streaming session.

<img width="1230" alt="screen shot 2018-06-01 at 10 16 04 pm" src="https://user-images.githubusercontent.com/1928509/40869460-6e79f872-65e9-11e8-92b6-c64d77324d15.png">

<img width="987" alt="screen shot 2018-06-01 at 10 16 55 pm" src="https://user-images.githubusercontent.com/1928509/40869465-866fb5c0-65e9-11e8-847f-05930517e717.png">

**Comment by msach22** [comment]
@laeroah Could you please provide crash logs and any other relevant information regarding the crashes?

**Comment by msach22** [comment]
@laeroah I'm going to go ahead and close this issue due to inactivity. Please re-open if you have any questions!
